blank_issues_enabled: false
contact_links:
  - name: There is an issue with @types/x
    url: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/new?category=issues-with-a-types-package
    about: 

  - name: Request a new @types library
    url: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/new?category=request-a-new-types-package
    about: Use the TypeScript Community Discord to talk with others about the site
